USE JOURNAL;
CREATE TABLE JOURNALS(
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    JNAME VARCHAR (255) NOT NULL,
    JCONTENT VARCHAR(255) NOT NULL,
    JDATE VARCHAR(255) NOT NULL,
    CATEGORYID VARCHAR(255) FOREIGN KEY REFERENCES CATEGORIES(ID) NOT NULL

)