USE JOURNAL;
GO
CREATE OR ALTER PROCEDURE updateUser(@ID VARCHAR(255),@EMAIL VARCHAR(255),@PASSWORD VARCHAR(255))
AS
BEGIN
UPDATE Users SET ID =@ID, EMAIL=@EMAIL, UPASSWORD=@PASSWORD WHERE ID =@ID
END;