USE JOURNAL
GO
CREATE OR ALTER PROCEDURE addJournal(@ID VARCHAR(255),@NAME VARCHAR(255),
@CONTENT VARCHAR(255),@JDATE VARCHAR (255),@CATEGORYID VARCHAR(255)) 
AS
BEGIN
INSERT INTO JOURNALS(ID,JNAME,JCONTENT,JDATE,CATEGORYID)
VALUES(@ID,@NAME,@CONTENT,@JDATE,@CATEGORYID)
END
