USE JOURNAL
GO
CREATE OR ALTER PROCEDURE updateJournal(@ID VARCHAR(255),@NAME VARCHAR(255),
@CONTENT VARCHAR(255),@JDATE VARCHAR (255),@CATEGORYID VARCHAR(255))
AS
BEGIN
UPDATE JOURNALS SET ID=@ID, JNAME=@NAME,JCONTENT=@CONTENT,JDATE=@JDATE,CATEGORYID=@CATEGORYID WHERE ID=@ID;
END